Comment out verify action results

diff --git a/bin/serva b/bin/serva
--- a/bin/serva
+++ b/bin/serva
@@ -82,11 +82,11 @@ manage_service() {
     esac
 
     # Verify action result
-    if [[ $? -eq 0 ]]; then
-        echo "Service '$service' ${ACTION}ed successfully."
-    else
-        echo "Failed to ${ACTION} service '$service'."
-    fi
+#    if [[ $? -eq 0 ]]; then
+#        echo "Service '$service' ${ACTION}ed successfully."
+#    else
+#        echo "Failed to ${ACTION} service '$service'."
+#    fi
 }
 
 # Main script logic
