Add extra mariadb installation steps for Alpine

diff --git a/bin/setup-db b/bin/setup-db
--- a/bin/setup-db
+++ b/bin/setup-db
@@ -34,6 +34,52 @@ if [[ $DTYPE == sqlite ]]; then
 
 elif [[ $DTYPE == mysql ]]; then
 
+    if [[ $OSTYP == alpine* ]]; then
+        echo "### Detected Alpine Linux"
+        if [[ ! -e /var/lib/mysql/ibdata1 ]]; then # Choose an essential file
+            echo "### MariaDB data directory is not initialized. Initializing..."
+
+            if rc-service mariadb status | grep -q "started"; then
+                echo "### Stopping MariaDB service..."
+                sudo rc-service mariadb stop
+            fi
+
+            echo "### Initializing MariaDB data directory..."
+            sudo mariadb-install-db \
+                --datadir=/var/lib/mysql \
+                --auth-root-authentication-method=normal
+
+            if [[ $? -ne 0 ]]; then
+                echo "### ERROR: Failed to initialize data directory."
+                exit 1
+            fi
+
+            echo "### Setting correct permissions on /var/lib/mysql..."
+            sudo chown -R mysql:mysql /var/lib/mysql
+
+            if [[ $? -ne 0 ]]; then
+                echo "### ERROR: Failed to change ownership of /var/lib/mysql."
+                exit 1
+            fi
+
+            echo "### Securing MariaDB installation..."
+            sudo mysql_secure_installation \
+                --auth-root-authentication-method=normal \
+                --set-root-password="$DPASS" \
+                --remove-anonymous-users=Y \
+                --disallow-remote-root-login=Y \
+                --remove-test-database=Y \
+                --reload-privilege-tables=Y
+
+            if [[ $? -ne 0 ]]; then
+                echo "### ERROR: Failed to secure MariaDB installation."
+                exit 1
+            fi
+        else
+            echo "### MariaDB data directory already initialized."
+        fi
+    fi
+
     if [[ -f ~/.my.cnf ]]; then
         echo "### Exists ~/.my.cnf (MySQL)"
     else
